### PR TITLE
Fix: permissions for labeler jobs

### PR DESCRIPTION
**Pull request by thekaveman**

### CODE REVIEW

**Comment by thekaveman** [comment]
Hmm the workflow says it ran successfully, yet the `actions` label was not added :thinking: 

https://github.com/compilerla/pems/actions/runs/12379265128/job/34553024820?pr=59

**Comment by lalver1** [comment]
Yeah I'm really confused about this. The workflow run is very specific about it being successful

image

so I don't know why the label wasn't added.

**Comment by thekaveman** [comment]
Maybe it needs to be merged to `main` for it to really take effect??

**Comment by lalver1** [comment]
Let's try that! I'll approve in a sec

**Review by lalver1 — APPROVED** [review]
👍

**Pull request merged**
